### ISSUE TITLE
"Error: Module did not self-register" in io.js 1.0.1

### ISSUE THREAD

**Issue by asilvas** [node-xmpp/node-expat#107]
```Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
    at bindings (/app/node_modules/node-expat/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/app/node_modules/node-expat/lib/node-expat.js:4:32)
```

**Comment by asilvas** [comment]
Worked fine until io.js -- haven't tested with node.js 0.11.x.

**Comment by lloydwatkin** [comment]
Apparently this needs a `nan` update, I'm just awaiting io.js support in `nvm` and I'll update.

**Comment by JohnAppleSeed-** [comment]
I think I may be having the same issue.
```
js-bson: Failed to load c++ bson extension, using pure JS version
/home/error/Documents/code/myprojects/BB/node_modules/bcrypt/node_modules/bindings/bindings.js:79
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
    at bindings (/home/error/Documents/code/myprojects/BB/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/home/error/Documents/code/myprojects/BB/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)
    at Module.load (module.js:341:32)
```
uname -a
```
Linux base 3.17.8-300.fc21.x86_64 #1 SMP Thu Jan 8 23:32:49 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Thank you io.js developers for giving me an alternative to empowering the authoritarian elitists.

**Comment by lloydwatkin** [comment]
This should be fixed now

**Comment by rochal** [comment]
I'm getting same issue with native node v0.11.14 on CentOS 6.5 running node-expat v2.3.5.

```
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/opt/project/node_modules/xml2json/node_modules/node-expat/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/opt/project/node_modules/xml2json/node_modules/node-expat/lib/node-expat.js:4:32)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```
