### ISSUE TITLE
Doesn't compile for iojs 2.0.0, 2.0.1

### ISSUE THREAD

**Issue by iliakan** [node-xmpp/node-expat#117]
Probably due to V8 upgrade.

```
> node-expat@2.3.7 install /js/javascript-nodejs/node_modules/node-xmpp/node_modules/node-expat
> node-gyp rebuild

  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
../deps/libexpat/lib/xmltok.c:471:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:484:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:504:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:517:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:730:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:749:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:762:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:775:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:871:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:890:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
10 warnings generated.
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  LIBTOOL-STATIC Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
In file included from ../node-expat.cc:1:
In file included from ../node_modules/nan/nan.h:80:
In file included from ../node_modules/nan/nan_new.h:190:
../node_modules/nan/nan_implementation_12_inl.h:181:66: error: too many arguments to function call, expected at most 2, have 4
  return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
         ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/iliakan/.node-gyp/2.0.1/deps/v8/include/v8.h:4188:3: note: 'New' declared here
  static Local<Signature> New(
  ^
../node-expat.cc:42:9: warning: 'NanRawString' is deprecated [-Wdeprecated-declarations]
        NanRawString(args[0], Nan::ASCII, NULL, encoding, 32, 0);
        ^
../node_modules/nan/nan.h:2110:33: note: 'NanRawString' has been explicitly marked deprecated here
NAN_DEPRECATED NAN_INLINE void* NanRawString(
                                ^
../node-expat.cc:150:9: warning: 'NanRawString' is deprecated [-Wdeprecated-declarations]
        NanRawString(args[0], Nan::ASCII, NULL, encoding, 32, 0);
        ^
../node_modules/nan/nan.h:2110:33: note: 'NanRawString' has been explicitly marked deprecated here
NAN_DEPRECATED NAN_INLINE void* NanRawString(
                                ^
../node-expat.cc:223:9: warning: 'NanRawString' is deprecated [-Wdeprecated-declarations]
        NanRawString(args[0], Nan::ASCII, NULL, encoding, 32, 0);
        ^
../node_modules/nan/nan.h:2110:33: note: 'NanRawString' has been explicitly marked deprecated here
NAN_DEPRECATED NAN_INLINE void* NanRawString(
                                ^
3 warnings and 1 error generated.
make: *** [Release/obj.target/node_expat/node-expat.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/pangyp/lib/build.js:271:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/bin/pangyp" "rebuild"
gyp ERR! cwd /js/javascript-nodejs/node_modules/node-xmpp/node_modules/node-expat
gyp ERR! node -v v2.0.1
gyp ERR! pangyp -v v2.1.0
gyp ERR! not ok
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "i" "--node-gyp=pangyp" "node-xmpp"
npm ERR! node v2.0.1
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE
```

**Comment by lloydwatkin** [comment]
You were correct. Released as 2.3.8. Thanks!
