### ISSUE TITLE
Cannot install on Windows

### ISSUE THREAD

**Issue by Waveharp** [node-xmpp/node-expat#147]
[npm-debug_log.txt](https://github.com/node-xmpp/node-expat/files/193929/npm-debug_log.txt)

{lamb} if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [E:\Documents\ Projects\Web Design\boardy\node_modules\node-expat\build\deps\libexpat\expat.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Documents\Projects\Web Design\boardy\node_modules\node-expat
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.9
npm WARN the-reduxening@1.0.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bgg"
npm ERR! node v4.2.6
npm ERR! npm  v3.8.1
npm ERR! code ELIFECYCLE

npm ERR! node-expat@2.3.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-expat@2.3.13 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-expat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

**Comment by HoosierMike** [comment]
Same here, one of the reason I am really starting to dislike node, to hokey

**Comment by sagitarious12** [comment]
Has nobody figured out a resolution to this issue? it seems it is still not functioning even after two years. This is kinda ridiculous..

**Comment by UncleGus** [comment]
Seems that way. Sad.

**Comment by UncleGus** [comment]
I have solved this. If you notice this part of the command ` else (node "" rebuild )` what I think is happening is that it is incorrectly evaluating `if not defined npm_config_node_gyp` as `false` and trying to run nothing instead of node-gyp. What you need to do is define your `npm_config_node_gyp` variable. You can do this like so:
`export npm_config_node_gyp=<PATH_TO_NODE_GYP_PACKAGE_FOLDER>` remember that Windows will need double backslashes. For me, it looked like this:
`export npm_config_node_gyp=C:\\Users\\781990\\AppData\\Roaming\\nvm\\v6.11.0\\node_modules\\node-gyp`

**Comment by UncleGus** [comment]
There is another step after my fix. When executing my code, the expat bindings were missing. To fix it, add the bin folder and node-gyp executable to the `npm_config_node_gyp` variable and run `node-gyp rebuild` in the `node_modules\node-expat` folder. e.g.
`export npm_config_node_gyp=C:\\Users\\781990\\AppData\\Roaming\\nvm\\v6.11.0\\node_modules\\node-gyp\\bin\\node-gyp.js`
`cd node_modules\node-expat`
`node-gyp rebuild`
